# # Install pre-commit hooks via
# pre-commit install

# modernizer: make sure our code-base is Python 3 ready
repos:
- repo: https://github.com/python-modernize/python-modernize.git
  rev: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    exclude: ^docs/
    args:
      - --write
      - --nobackups
      - --nofix=dict_six

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    types: [python]
    exclude: >
      (?x)^(
          docs/.*|
      )$
    args: ['-i']

- repo: local
  hooks:
    # pylint: static code analysis
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
